author: 'juhlinus'

name: 'Easy Coding Standard Github Action'

description: 'A Github Action for simplify/ecs'

inputs:
  files:
    description: 'Which files to run on'
    required: true

  composer_ignore_platform_reqs:
    required: false
    default: false
    description: 'Whether or not the --ignore-platform-reqs flag is passed to Composer'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}